# --- SHI BEGIN ---
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

set -g mouse on
set-window-option -g mode-keys vi
set -g history-limit 10000
set -g allow-rename off

set -g @plugin 'tmux-plugins/tmux-yank'
set -g @yank_selection_mouse 'clipboard'
set -g @plugin 'tmux-plugins/tmux-logging'

set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'

run '~/.tmux/plugins/tpm/tpm'

# --- SHI END ---
